// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:finlog/models/bill_data.dart';
import 'package:finlog/models/bill_item.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BillDataAdapter());
    registerAdapter(BillItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BillDataAdapter());
    registerAdapter(BillItemAdapter());
  }
}
