name: Flutter Build and Release APK on Push to Main

on:
  push:
    branches: [ main ]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- Get Semantic Version from pubspec.yaml ---
      - name: Read pubspec.yaml semantic version
        id: pubspec
        run: |
          VERSION_LINE=$(grep '^version:' pubspec.yaml)
          SEMANTIC_VERSION=$(echo "$VERSION_LINE" | sed 's/version: //g' | sed 's/+\.*//g' | tr -d '[:space:]')
          echo "semantic_version=$SEMANTIC_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3' # Adjusted, change if needed

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env

      # --- Build APK with Overridden Version ---
      - name: Build APK
        run: flutter build apk --release --build-name=${{ steps.pubspec.outputs.semantic_version }} --build-number=${{ github.run_number }}

      # --- Release Steps (using the version info) ---
      - name: Create Release Tag Name
        id: create_tag
        run: echo "tag_name=v${{ steps.pubspec.outputs.semantic_version }}+${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
          release_name: "Release v${{ steps.pubspec.outputs.semantic_version }}+${{ github.run_number }}"
          # --- IMPORTANT: Updated body to use commit info ---
          body: |
            Automated release triggered by push to main.
            **Version:** v${{ steps.pubspec.outputs.semantic_version }}+${{ github.run_number }}
            
            **Commit Details:**
            ${{ github.event.head_commit.message }}
            
            Author: ${{ github.event.head_commit.author.name }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release APK Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release-v${{ steps.pubspec.outputs.semantic_version }}+${{ github.run_number }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Build Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-v${{ steps.pubspec.outputs.semantic_version }}+${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk